# -*- coding: utf-8 -*-
"""FA3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Ivb9V_mPqhfse1Dy_NgsPxMIU2yse5e
"""

import pandas as pd
import numpy as np
from scipy import stats

# Sample data
data = [88, 45, 53, 86, 33, 86, 85, 30, 89, 53, 41, 96, 56, 38, 62,
        71, 51, 86, 68, 29, 28, 47, 33, 37, 25, 36, 33, 94, 73, 46,
        42, 34, 79, 72, 88, 99, 82, 62, 57, 42, 28, 55, 67, 62, 60,
        96, 61, 57, 75, 93, 34, 75, 53, 32, 28, 73, 51, 69, 91, 35]

# Calculate descriptive measures
q1 = np.percentile(data, 25)
q2 = np.median(data)
q3 = np.percentile(data, 75)
d9 = np.percentile(data, 90)
p95 = np.percentile(data, 95)
std_deviation = np.std(data)
variance = np.var(data)
min_value = min(data)
max_value = max(data)
mean = np.mean(data)
mode = stats.mode(data).mode[0]

# Create a DataFrame for the table
descriptive_table = pd.DataFrame({
    'Measure': ['Q1 (25th Percentile)', 'Q2 (Median - 50th Percentile)', 'Q3 (75th Percentile)',
                'D9 (90th Percentile)', 'P95 (95th Percentile)', 'Standard Deviation', 'Variance',
                'Minimum', 'Maximum', 'Mean', 'Median', 'Mode'],
    'Value': [q1, q2, q3, d9, p95, std_deviation, variance, min_value, max_value, mean, q2, mode]
})

# Print the table
print(descriptive_table)